"""Local discovery seeds, not live legal status evidence."""
LEGAL_AREAS = [
    "constitucional", "administrativo", "tributario", "civil", "processual_civil",
    "penal", "processual_penal", "trabalhista", "previdenciario", "empresarial",
    "consumidor", "digital", "ambiental", "eleitoral", "familia",
    "infancia_juventude", "licitacoes_contratos", "transparencia", "compliance"
]

LEGISLATION_CATALOG = [
    {
        "title": "Constituição da República Federativa do Brasil de 1988",
        "act_type": "constituicao",
        "number": "CF/1988",
        "year": 1988,
        "area": "constitucional",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Texto constitucional vigente da República Federativa do Brasil.",
        "url": "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
        "aliases": ["constituicao", "cf", "cf88", "constituicao federal", "constituicao de 1988"],
        "themes": ["direitos fundamentais", "organizacao do estado", "poderes", "tributacao", "ordem economica"]
    },
    {
        "title": "Emenda Constitucional nº 132/2023",
        "act_type": "emenda_constitucional",
        "number": "EC 132/2023",
        "year": 2023,
        "area": "tributario",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Emenda constitucional da reforma tributária sobre o consumo.",
        "url": "https://www.planalto.gov.br/ccivil_03/constituicao/emendas/emc/emc132.htm",
        "aliases": ["reforma tributaria", "ec 132", "ec 132/2023", "tributaria", "ibs", "cbs", "imposto seletivo"],
        "themes": ["reforma tributaria", "consumo", "tributos", "ibs", "cbs", "imposto seletivo"]
    },
    {
        "title": "Estatuto da Criança e do Adolescente",
        "act_type": "estatuto",
        "number": "Lei 8.069/1990",
        "year": 1990,
        "area": "infancia_juventude",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Dispõe sobre o Estatuto da Criança e do Adolescente.",
        "url": "https://www.planalto.gov.br/ccivil_03/leis/l8069.htm",
        "aliases": ["eca", "estatuto da crianca e do adolescente", "crianca", "adolescente"],
        "themes": ["infancia", "juventude", "protecao integral", "menor", "adolescente"]
    },
    {
        "title": "Lei Geral de Proteção de Dados Pessoais",
        "act_type": "lei_ordinaria",
        "number": "Lei 13.709/2018",
        "year": 2018,
        "area": "digital",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Lei Geral de Proteção de Dados Pessoais.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm",
        "aliases": ["lgpd", "protecao de dados", "dados pessoais", "privacidade"],
        "themes": ["dados pessoais", "tratamento de dados", "privacidade", "seguranca da informacao"]
    },
    {
        "title": "Marco Civil da Internet",
        "act_type": "lei_ordinaria",
        "number": "Lei 12.965/2014",
        "year": 2014,
        "area": "digital",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Estabelece princípios, garantias, direitos e deveres para o uso da internet no Brasil.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l12965.htm",
        "aliases": ["marco civil", "internet", "marco civil da internet"],
        "themes": ["internet", "provedores", "responsabilidade civil", "dados", "rede"]
    },
    {
        "title": "Código de Defesa do Consumidor",
        "act_type": "codigo",
        "number": "Lei 8.078/1990",
        "year": 1990,
        "area": "consumidor",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Dispõe sobre a proteção do consumidor.",
        "url": "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
        "aliases": ["cdc", "consumidor", "defesa do consumidor"],
        "themes": ["consumo", "fornecedor", "produto", "servico", "responsabilidade"]
    },
    {
        "title": "Consolidação das Leis do Trabalho",
        "act_type": "codigo",
        "number": "Decreto-Lei 5.452/1943",
        "year": 1943,
        "area": "trabalhista",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Consolidação das Leis do Trabalho.",
        "url": "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm",
        "aliases": ["clt", "trabalho", "leis do trabalho", "direito do trabalho"],
        "themes": ["emprego", "contrato de trabalho", "jornada", "ferias", "salario"]
    },
    {
        "title": "Código Civil",
        "act_type": "codigo",
        "number": "Lei 10.406/2002",
        "year": 2002,
        "area": "civil",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Institui o Código Civil.",
        "url": "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
        "aliases": ["codigo civil", "cc", "civil"],
        "themes": ["obrigacoes", "contratos", "responsabilidade civil", "familia", "sucessoes"]
    },
    {
        "title": "Código de Processo Civil",
        "act_type": "codigo",
        "number": "Lei 13.105/2015",
        "year": 2015,
        "area": "processual_civil",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Código de Processo Civil.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
        "aliases": ["cpc", "processo civil", "codigo de processo civil"],
        "themes": ["procedimento", "recursos", "tutela", "cumprimento de sentenca", "execucao"]
    },
    {
        "title": "Código Penal",
        "act_type": "codigo",
        "number": "Decreto-Lei 2.848/1940",
        "year": 1940,
        "area": "penal",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Código Penal brasileiro.",
        "url": "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
        "aliases": ["codigo penal", "cp", "penal"],
        "themes": ["crimes", "penas", "parte geral", "parte especial"]
    },
    {
        "title": "Código de Processo Penal",
        "act_type": "codigo",
        "number": "Decreto-Lei 3.689/1941",
        "year": 1941,
        "area": "processual_penal",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Código de Processo Penal brasileiro.",
        "url": "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm",
        "aliases": ["codigo de processo penal", "cpp", "processo penal"],
        "themes": ["inquerito", "acao penal", "provas", "prisao", "recursos"]
    },
    {
        "title": "Lei de Licitações e Contratos Administrativos",
        "act_type": "lei_ordinaria",
        "number": "Lei 14.133/2021",
        "year": 2021,
        "area": "licitacoes_contratos",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Lei geral de licitações e contratos administrativos.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm",
        "aliases": ["14133", "lei 14133", "nova lei de licitacoes", "licitacoes", "contratos administrativos"],
        "themes": ["licitacao", "contrato administrativo", "pregao", "concorrencia", "dispensa", "inexigibilidade"]
    },
    {
        "title": "Lei de Acesso à Informação",
        "act_type": "lei_ordinaria",
        "number": "Lei 12.527/2011",
        "year": 2011,
        "area": "transparencia",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Regula o acesso a informações previsto na Constituição.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm",
        "aliases": ["lai", "lei de acesso a informacao", "acesso a informacao", "transparencia"],
        "themes": ["transparencia", "informacao publica", "dados publicos"]
    },
    {
        "title": "Lei Anticorrupção Empresarial",
        "act_type": "lei_ordinaria",
        "number": "Lei 12.846/2013",
        "year": 2013,
        "area": "compliance",
        "official_source": "planalto",
        "status": "vigente",
        "summary": "Responsabilização administrativa e civil de pessoas jurídicas por atos contra a administração pública.",
        "url": "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12846.htm",
        "aliases": ["lei anticorrupcao", "12846", "compliance", "integridade"],
        "themes": ["corrupcao", "responsabilizacao", "programa de integridade", "administracao publica"]
    }
]
